def display_weather(weather_data):
    print("=" * 40)
    print("        WEATHER REPORT")
    print("=" * 40)
    print(f"City         : {weather_data['name']}")
    print(f"Country      : {weather_data['sys']['country']}")
    print(f"Temperature  : {weather_data['main']['temp']} °C")
    print(f"Feels Like   : {weather_data['main']['feels_like']} °C")
    print(f"Humidity     : {weather_data['main']['humidity']} %")
    print(f"Pressure     : {weather_data['main']['pressure']} hPa")
    print(f"Weather      : {weather_data['weather'][0]['main']}")
    print(f"Description  : {weather_data['weather'][0]['description']}")
    print(f"Wind Speed   : {weather_data['wind']['speed']} m/s")
    print(f"Visibility   : {weather_data['visibility']} meters")
    print("=" * 40)